# Application Configuration - Production Environment

http:
  listener:
    host: "0.0.0.0"
    port: "8081"
    basePath: "/api/v1"
  request:
    timeout: "60000"
    retryCount: "5"
    retryInterval: "3000"

api:
  id: "${api.id}"
  name: "netsuite-salesforce-order-inventory-api"
  version: "v1"

netsuite:
  api:
    host: "system.netsuite.com"
    port: "443"
    basePath: "/rest/v1"
    protocol: "HTTPS"

salesforce:
  api:
    host: "login.salesforce.com"
    port: "443"
    basePath: "/services/data/v58.0"
    protocol: "HTTPS"

objectstore:
  idMapping:
    entryTtl: "48"
    entryTtlUnit: "HOURS"
    maxEntries: "50000"

logging:
  level: "INFO"
  maskFields: "password,secret,token,authorization"
